---
title: "Rapport_personlige_stemmer"
editor_options: 
  chunk_output_type: console
---


## Rangering valgte personer

```{r}
## Kobler med parti kvotienter for at kunne rangere valgorden overall for personer

# TODO: OBS, er afhængig af bestemt sortering. Antager overall rank er stigende, grupperet på partier.
kvotienter_partier_til_pers <- kvotienter_partier %>% 
  filter(mandat_parti) %>% 
  select(bogstav, overall_rank) %>% 
  nest_by(bogstav)

pers_ranking2 <- pers_ranking %>% 
  left_join(kvotienter_partier_til_pers, by = "bogstav") %>% 
  rowwise() %>%
  mutate(overall_rank = list(data[valgt_rank, "overall_rank"])) %>% 
  select(-data) %>% 
  unnest(cols = overall_rank)


```


Antagelse at alle er opstillet sideordnet (/kan *ikke* tage højde for partilister)

```{r}

kable(pers_ranking2 %>% 
        filter(mandat) %>% 
        select(bogstav, parti, navn, personlige_stemmer, valgt_rank, overall_rank) %>% 
        arrange(bogstav, valgt_rank, overall_rank),
      format = "html",
      caption = "Valgte personer (Inkl. rang)")

```

```{r}

kable(pers_ranking2 %>% 
        filter(mandat) %>% 
        select(bogstav, parti, navn, personlige_stemmer, valgt_rank, overall_rank) %>% 
        arrange(overall_rank),
      format = "html",
      caption = "Total rang for valgte personer")

```

## Rangering alle opstillede personer

```{r}

kable(pers_ranking2 %>% 
        select(bogstav, parti, navn, personlige_stemmer, valgt_rank, stedfortræder_rank) %>% 
        arrange(bogstav, valgt_rank, stedfortræder_rank), 
      format = "html",
      caption = "Rangorden alle personer")

```
