project:
  type: website
  output-dir: "docs"
  render: 
    - index.qmd
    - about.qmd
    - FT_rapport.qmd
    - EP_rapport.qmd

website:
  title: "thranholm.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - FT_rapport.qmd
      - EP_rapport.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

