project:
  type: website
  render: 
    - index.qmd
    - about.qmd

website:
  title: "Thranholm.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

