project:
  type: website
  output-dir: "docs"
  render: 
    - index.qmd
    - about.qmd
    - ftvalg/rapport.qmd

website:
  title: "thranholm.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: hejsa
      - ftvalg/rapport.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

