filters: 
  - shinylive

project:
  type: website
  output-dir: "docs"
  render: 
    - index.qmd
    - about.qmd
    - FT_rapport.qmd
    - stedmandat.qmd
    - komvalg_shiny.qmd
    - "epvalg/EP_rapport_2009.qmd"
    - "epvalg/EP_rapport_2014.qmd"
    - "epvalg/EP_rapport_2019.qmd"
    - "epvalg/EP_rapport_2024.qmd"
    - mio6DK.qmd
    - fodbold_kalender/00_danner_fodbolddata_sportradar.qmd
    - "fodbold_kalender/Tysk fodboldkort2.qmd"
    # - "fodbold_kalender/Tysk fodboldkort_amateur.qmd"
    - "fodbold_kalender/Dansk fodboldkort2.qmd"
    - "fodbold_kalender/Belgisk fodboldkort2.qmd"

website:
  title: "Emil Thranholm"
  site-url: "https://thranholm.github.io/"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - FT_rapport.qmd
      - text: Europaparlamentsvalg
        menu:
          - href: "epvalg/EP_rapport_2009.qmd"
            text: "2009"
          - href: "epvalg/EP_rapport_2014.qmd"
            text: "2014"
          - href: "epvalg/EP_rapport_2019.qmd"
            text: "2019"
          - href: "epvalg/EP_rapport_2024.qmd"
            text: "2024"
      - href: mio6DK.qmd
        text: 6 mio danskere
      - text: Fodboldkalender
        menu:
          - href: "fodbold_kalender/Tysk fodboldkort2.qmd"
            text: Tyskland
          - href: "fodbold_kalender/Tysk fodboldkort_amateur.qmd"
            text: Tyskland Regionalliga
          - href: "fodbold_kalender/Dansk fodboldkort2.qmd"
            text: Danmark
          - href: "fodbold_kalender/Belgisk fodboldkort2.qmd"
            text: Belgien
      
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

