project:
  type: website
  output-dir: "docs"
  render: 
    - index.qmd
    - about.qmd
    - FT_rapport.qmd
    - render_ep_rapport.qmd
    - mio6DK.qmd

website:
  title: "Emil Thranholm"
  site-url: "https://thranholm.github.io/"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - FT_rapport.qmd
      - href: render_ep_rapport.qmd
      - text: Europaparlamentsvalg
      - EP_rapport.qmd
      - href: mio6DK.qmd
        text: 6 mio danskere
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

