project:
  type: website
  output-dir: "docs"
  render: 
    - index.qmd
    - about.qmd
    - FT_rapport.qmd
    - stedmandat.qmd
    - "epvalg/EP_rapport_2009.qmd"
    - "epvalg/EP_rapport_2014.qmd"
    - "epvalg/EP_rapport_2019.qmd"
    - mio6DK.qmd
    - fodbold_kalender/00_danner_fodbolddata.qmd
    - "fodbold_kalender/Tysk fodboldkort.qmd"
    - "fodbold_kalender/Dansk fodboldkort.qmd"

website:
  title: "Emil Thranholm"
  site-url: "https://thranholm.github.io/"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - FT_rapport.qmd
      - href: render_ep_rapport.qmd
      - text: Europaparlamentsvalg
        menu:
          - href: "epvalg/EP_rapport_2009.qmd"
            text: "2009"
          - href: "epvalg/EP_rapport_2014.qmd"
            text: "2014"
          - href: "epvalg/EP_rapport_2019.qmd"
            text: "2019"
      - href: mio6DK.qmd
        text: 6 mio danskere
      - text: Fodboldkalender
        menu: 
          - href: "fodbold_kalender/Tysk fodboldkort.qmd"
            text: Tyskland
          - href: "fodbold_kalender/Dansk fodboldkort.qmd"
            text: Danmark
      
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

