---
title: "Fodboldkalender"
output: html_document
editor_options: 
  chunk_output_type: console
---



```{r}
#| label: kører programmer
#| message: false
#| echo: false

# Sys.setenv(GDAL_DATA = "/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/sf/gdal")
# Sys.setenv(OGR_ENABLE_PARTIAL_REPROJECTION = TRUE)
# Sys.setenv(PROJ_GDAL_DATA_COPY=TRUE)

source("Pakker og api.R")
source("Kampprogram fra api.R")
source("Finder geodata.R")
source("laver plots.R")

```


OBS! Kamptidspunkter bør tjekkes efter. For 3. Liga især er de ikke altid retvisende.

Seneste opdatering: `r format(with_tz(Sys.time(), "CET"), "%d/%m/%Y %H:%M:%S")`

```{r}
#| label: laver kort
#| fig-align: left
#| echo: false

p_load(tidyverse, ggiraph, cowplot)
# map(kampprogram_nested$plot, ~girafe(ggobj = plot_grid(plotlist = )  print(.x)))
girafe(ggobj = plot_grid(plotlist = kampprogram_nested$plot, ncol = 1, nrow = 42, scale = 1)
       , width_svg = 7, height_svg = 250)

# /opt/homebrew/Cellar/proj/9.3.1

```



