name: automatisk opdatering

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

on:
  schedule:
    - cron: "10 7 * * *"
  workflow_dispatch:
  #push:
  #  branches: ['main']
  

jobs:
 quarto-render:
   runs-on: ubuntu-latest
   steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Quarto
      uses: quarto-dev/quarto-actions/setup@v2

    - name: apt-get
      run: apt-get update
      # alle mulige pakker, der har givet fejl
    - name: Install libudunits2 libgdal libgeos libproj
      run: sudo apt-get install libudunits2-dev libgdal-dev libgeos-dev libproj-dev

        # From https://github.com/r-lib/actions/tree/v2-branch/setup-r
    - name: setup-R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.3.1'
      
    - name: Install R Dependencies
      uses: r-lib/actions/setup-renv@v2
      with:
        cache-version: 1
    
    - name: da_DK.UTF-8
      run: |
        sudo locale-gen da_DK.UTF-8
        sudo update-locale LANG=da_DK.UTF-8

      # NOTE: If Publishing to GitHub Pages, set the permissions correctly (see top of this yaml)
    - name: Publish to GitHub Pages (and render)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # this secret is always available for github actions
        FODBOLD_KEY: ${{ secrets.FODBOLD_KEY }}
        PASS: ${{ secrets.PASS }}
        LANG: "da_DK.UTF-8"
      uses: quarto-dev/quarto-actions/publish@v2
      with:
        target: gh-pages
        # path: docs

