name: test et doku

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

on:
  workflow_dispatch:
  #push:
  #  branches: ['main']
  

jobs:
 quarto-render:
   runs-on: ubuntu-latest
   steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Update apt package lists
      run: |
        sudo apt-get update
        sudo apt-get install --fix-missing

# alle mulige pakker, der har givet fejl
    - name: Install libudunits2 libgdal libgeos libproj
      run: sudo apt-get install libgdal-dev libudunits2-dev libgeos-dev libproj-dev

    - name: Set up Quarto
      uses: quarto-dev/quarto-actions/setup@v2

        # From https://github.com/r-lib/actions/tree/v2-branch/setup-r
    - name: setup-R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.3.1'
      
    - name: Install R Dependencies
      uses: r-lib/actions/setup-renv@v2
      with:
        cache-version: 1
    
    - name: da_DK.UTF-8
      run: |
        sudo locale-gen da_DK.UTF-8
        sudo update-locale LANG=da_DK.UTF-8

      # NOTE: If Publishing to GitHub Pages, set the permissions correctly (see top of this yaml)
    - name: Render index
      env:
        LANG: "da_DK.UTF-8"
      uses: quarto-dev/quarto-actions/render@v2
      with:
        path: index.qmd

    - name: Render mio6DK
      env:
        LANG: "da_DK.UTF-8"
      uses: quarto-dev/quarto-actions/render@v2
      with:
        path: mio6DK.qmd

    - name: Publish to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
        keep_files: true
